#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point
#       to that shell before running this script, e.g.:
#           SHELL=/usr/bin/ksh ./gradlew
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available file descriptors if possible.
if [ -f /proc/sys/fs/file-max ]; then
    MAX_FD=$( cat /proc/sys/fs/file-max )
else
    MAX_FD=65536
fi

# Discard cd output to avoid confusion in output
if command -v ulimit > /dev/null 2>&1; then
    ulimit -n "$MAX_FD" || true
fi

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "$( uname -s )" in        #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java > /dev/null 2>&1; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
Java安装的位置。"
Fi
Fi

#收集java命令的所有参数，按相反顺序堆叠：
命令行中的#*args
#*主类名
#*类路径'gradle-Launcher.jar'
#*应用程序路径'梯度/包裹物/梯度包裹物。属性'
#*包装器脚本使用的JVM参数
#*传递给Java命令的JVM参数。

设置--\
org.gradle.wrapper.GradleWrapperMain\
"$@"

#使用“xargs”解析带引号的参数。
#
#使用-n1，它每行输出一个参数，去掉引号和反斜杠。
#
#在Bash中，我们可以简单地：
#
#readarray ARGS<<(xargs-n1<<<"$var")&&
#set--"${ARGS[@]}""$@"
#
#但是POSIX shell既没有数组也没有命令替换，所以我们
#后处理每个arg(作为sed的输入行)以反斜杠转义任何
#字符，该字符可能是shell元字符，然后使用eval来反转
#该进程(同时保持参数之间的分隔)，并换行
#整件事作为一个单一的“set”语句。
#
#如果这些变量中的任何一个包含换行符或
#不匹配的引号。
#

eval“”集合--$(
printf“%s”\n“$DEFAULT_JVM_OPTS$JAVA_OPTS$Gradle_OPTS”|
xargs-n1|
SED的~[^-[：alnum：]+，./：=@_]~\\&~g；'|
TR“\n”
)" '"$@"'

exec"$JAVACMD""$@"
